name: Build and Upload Go Binary

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build binary
        run: go build -o azure-inventory-cli-tool

      - name: Upload binary to repository
        uses: actions/upload-artifact@v4
        with:
          name: azure-inventory-cli-tool
          path: azure-inventory-cli-tool